### ISSUE TITLE
Error whilst 

### ISSUE THREAD

**Issue by Tommo565** [fhamborg/Giveme5W1H#25]
I'm getting an error when trying to run `extractor.parse(doc)`. I've tried on both my text and also the example text and it occurs both times.

Error as follows:

```
Could not handle incoming annotation
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/Giveme5W1H/extractor/extractor.py", line 20, in run
    extractor.process(document)
  File "/usr/local/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/abs_extractor.py", line 41, in process
    self._evaluate_candidates(document)
  File "/usr/local/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/action_extractor.py", line 104, in _evaluate_candidates
    if any(doc_coref.values()):
AttributeError: 'list' object has no attribute 'values'
```

Thanks!

**Comment by Tommo565** [comment]
Version is giveme5w1h==1.0.12

**Comment by Tommo565** [comment]
Let me know if there's anything else you need... This is my first issue!

**Comment by fhamborg** [comment]
The error seems to be coming from Stanford CoreNLP, not our tool. Could you provide a full, minimal code example, with which I can reproduce the error, including also an article text, please?

**Comment by onesixzerotwo** [comment]
Hi, 
I faced similar issue too. I ran _giveme5w1h-rest_ command, then at the page, I ran '_run example_' and faced this error.

Output at run giveme5w1h-rest console
```
  File "/usr/local/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/abs_extractor.py", line 41, in process
    self._evaluate_candidates(document)
  File "/usr/local/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/action_extractor.py", line 104, in _evaluate_candidates
    if any(doc_coref.values()):
AttributeError: 'list' object has no attribute 'values'
```
Output at corenlp console
```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 53 more
```
 - OS: MacOS 10.14.3
 - Python Version 3.6.2
 - Giveme5W1H Version 1.0.13
 - Stanford CoreNLP Version
- Java Version 8 Update 201

**Comment by WeeklyUfo** [comment]
> Let me know if there's anything else you need... This is my first issue!

I am experiencing the exact same error code. Did you find a fix for this?
