### ISSUE TITLE
Error message when running parse_single_from_code.py

### ISSUE THREAD

**Issue by pi201800** [fhamborg/Giveme5W1H#29]
Hi, 

I tried to run the example code parse_single_from_code.py and received this error message:

$ python parse_single_from_code.py 
No extractors passed: initializing default configuration.
No combinedScorers passed: initializing default configuration.
/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/examples/caches/Nominatim.prickle CACHED: Mazar-i-Sharif: مزار شریف, بلخ, افغانستان
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/anaconda2/envs/Giveme5W1H/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/extractor/extractor.py", line 20, in run
    extractor.process(document)
  File "/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/abs_extractor.py", line 40, in process
    self._extract_candidates(document)
  File "/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/environment_extractor.py", line 147, in _extract_candidates
    self._cache_nominatim.cache(location_string, location)
  File "/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/extractor/tools/key_value_cache.py", line 58, in cache
    self.persist()
  File "/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/extractor/tools/key_value_cache.py", line 43, in persist
    with open(self._cache_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda2/envs/Giveme5W1H/lib/python3.6/site-packages/Giveme5W1H/examples/caches/Nominatim.prickle'

versions: 
 - OS: MacOS 10.14.1 
 - Python 3.6.8
 - Giveme5W1H-1.0.13
 - Stanford CoreNLP Version : stanford-corenlp-full-2017-06-09

Thanks.

**Comment by fhamborg** [comment]
please use the bug report template, thanks.
