### ISSUE TITLE
AttributeError: 'list' object has no attribute 'values'

### ISSUE THREAD

**Issue by CZFuChason** [fhamborg/Giveme5W1H#43]
**Describe the bug**
I just installed giveme5W1H by following the tutorial and tried to run a simple example (parse_single_from_code.py) in the terminal.

but it pops out the error as below:

No extractors passed: initializing default configuration.
No combinedScorers passed: initializing default configuration.
edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/chason/5w1h/lib/python3.6/site-packages/Giveme5W1H/extractor/extractor.py", line 20, in run extractor.process(document)
  File "/home/chaosn/5w1h/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/abs_extractor.py", line 41, in process self._evaluate_candidates(document)
  File "/home/chaosn/5w1h/lib/python3.6/site-packages/Giveme5W1H/extractor/extractors/action_extractor.py", line 104, in _evaluate_candidates
    if any(doc_coref.values()):
AttributeError: 'list' object has no attribute 'values'

**Expected behavior**
Can anyone tell me how to fix this problem?

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu18.04
 - Python Version 3.6
 - Giveme5W1H Version 1.0.17
 - Stanford CoreNLP Version 0.0.14

**Comment by wangda1** [comment]
I just had the same problem and find the Standford-corenlp version is not proper. You can follow this issue https://github.com/fhamborg/Giveme5W1H/issues/33 and download suitable version.

**Comment by TitasDas** [comment]
Using a different version of JDK helped solved this issue for me. Uninstalled the default version and installed JDK 8 and then ran the coreNLP server. This solution is also covered in a previously reported issue 32.
