### ISSUE TITLE
Python 3.8 compatibility issue

### ISSUE THREAD

**Issue by MarwaEssam** [fhamborg/Giveme5W1H#55]
I have the following code and I am trying to execute the library

  

> **extractor = MasterExtractor()
>     date_publish = '2016-11-10 07:44:00'
>     doc = Document.from_text(titleshort, date_publish)
>     print('doc annotation process....')
>     doc = extractor.parse(doc)
>     top_who_answer = doc.get_top_answer('who').get_parts_as_text()
>     top_what_answer = doc.get_top_answer('what').get_parts_as_text()
>     top_when_answer = doc.get_top_answer('when').get_parts_as_text()
>     top_where_answer = doc.get_top_answer('where').get_parts_as_text()
>     top_why_answer = doc.get_top_answer('why').get_parts_as_text()
>     top_how_answer = doc.get_top_answer('how').get_parts_as_text()
>     print(top_who_answer)
>     print(top_what_answer)
>     print(top_when_answer)
>     print(top_where_answer)
>     print(top_why_answer)
>     print(top_how_answer)**

**I got the following error after solving all other issues as appeared here on the repository.**

> **Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/Users/omarsayed/PycharmProjects/GiveMe5W1HTest/venv/lib/python3.8/site-packages/Giveme5W1H/extractor/extractor.py", line 20, in run
>     extractor.process(document)
>   File "/Users/omarsayed/PycharmProjects/GiveMe5W1HTest/venv/lib/python3.8/site-packages/Giveme5W1H/extractor/extractors/abs_extractor.py", line 40, in process
>     self._extract_candidates(document)
>   File "/Users/omarsayed/PycharmProjects/GiveMe5W1HTest/venv/lib/python3.8/site-packages/Giveme5W1H/extractor/extractors/cause_extractor.py", line 92, in _extract_candidates
>     for candidate in self._evaluate_tree(tree):
>   File "/Users/omarsayed/PycharmProjects/GiveMe5W1HTest/venv/lib/python3.8/site-packages/Giveme5W1H/extractor/extractors/cause_extractor.py", line 131, in _evaluate_tree
>     if sibling.label() == 'VP' and "('NP'" in sibling.unicode_repr():
> AttributeError: 'ParentedTree' object has no attribute 'unicode_repr'**

**_Is this error related to the higher python version? If yes then how to solve it. I don't prefer to roll back to earlier versions of python. Thanks_**

**Versions **
 - OS: [MacOS 10.15.6
 - Python Version [3.8]
 - Giveme5W1H Version [the one installed using pip3 install giveme5w1h . 1.0.17 I guess]
 - Stanford CoreNLP Version (The one again installed using : giveme5w1h-corenlp install)

**Comment by MarwaEssam** [comment]
I updated the caseExtractor.py file as suggested and it solved the issue. I have now the following output for the full text input: 

> All German staff from the consulate
> were unharmed , according to the foreign ministry
> late Thursday
> Kunduz
> The Taliban
> the volatile province of Kunduz that left 32 civilians dead
