### ISSUE TITLE
Cannot start giveme5w1h-rest due to: 'Giveme5W1H.examples' package was not installed in a way that PackageLoader understands

### ISSUE THREAD

**Issue by angsuman** [fhamborg/Giveme5W1H#73]
**Describe the bug**
Cannot start giveme5w1h-rest due to: 'Giveme5W1H.examples' package was not installed in a way that PackageLoader understands

**To Reproduce**
Install as usual:
```
pip3 install giveme5w1h
giveme5w1h-corenlp install
```
Successfully run: `giveme5w1h-corenlp`
Then try to run `giveme5w1h-rest`

**Expected behavior**
The program should run without errors.

**Log**
```
giveme5w1h-rest
Traceback (most recent call last):
  File "/home/angsuman/.local/bin/giveme5w1h-rest", line 5, in <module>
    from Giveme5W1H.examples.extracting.server import main
  File "/home/angsuman/.local/lib/python3.8/site-packages/Giveme5W1H/examples/extracting/server.py", line 43, in <module>
    loader=PackageLoader('Giveme5W1H.examples', 'Giveme5W1H.extracting'),
  File "/home/angsuman/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'Giveme5W1H.examples' package was not installed in a way that PackageLoader understands.
```

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python Version 3.9.10
 - Giveme5W1H Version latest from github
 - Stanford CoreNLP Version latest

**Comment by nitinthewiz** [comment]
Just saw this on Mac OS Catalina with Python 3.9.10 as well.

The commonality is the python version?

**Comment by angsuman** [comment]
> Just saw this on Mac OS Catalina with Python 3.9.10 as well.
> 
> The commonality is the python version?

I am using Python 3.8.
